add_newline = true

format = """
[](#0D1821)\
$os\
$username\
[](bg:#344966 fg:#0D1821)\
$directory\
[](fg:#344966 bg:#B4CDED)\
$git_branch\
$git_status\
[](fg:#B4CDED bg:#F0F4EF)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#F0F4EF bg:#BFCC94)\
$docker_context\
[](fg:#BFCC94 bg:#C297B8)\
$time\
[ ](fg:#C297B8)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#0D1821"
style_root = "bg:#0D1821"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#0D1821"
disabled = true # Disabled by default

[directory]
style = "bg:#344966"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#BFCC94"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#B4CDED"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#B4CDED"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#F0F4EF"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#C297B8"
format = '[ $time ]($style)'
